const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Flash,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.UnlockOrientation,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Text.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{IMG_: 0},
	{Sine: 0},
	{IMG_2: 0},
	{IMG_3: 0},
	{IMG_4: 0},
	{IMG_5: 0},
	{IMG_6: 0},
	{IMG_7: 0},
	{base_x: 0},
	{base_y: 0},
	{target_number: 0},
	{target_tween: 0},
	{title: 0},
	{state: 0},
	{LiteTween: 0},
	{state_tween: 0},
	{tombol: 0},
	{Browser: 0},
	{Touch: 0},
	{Keyboard: 0},
	{tr1: 0},
	{tr2: 0},
	{headline: 0},
	{camera: 0},
	{info_layer: 0},
	{Platform: 0},
	{Jumpthru: 0},
	{Flash: 0},
	{tokoh: 0},
	{savegame: 0},
	{LocalStorage: 0},
	{solids: 0},
	{IMG_8: 0},
	{heart: 0},
	{profil: 0},
	{items: 0},
	{ambil_btn: 0},
	{IMG_9: 0},
	{dark: 0},
	{Text: 0},
	{jeda: 0},
	{soal: 0},
	{jawaban: 0},
	{a: 0},
	{b: 0},
	{c: 0},
	{d: 0},
	{e: 0},
	{questionBox: 0},
	{Audio: 0},
	{funfact: 0},
	{tracker: 0},
	{first_move: 0},
	{enemy_state: 0},
	{onRadius: 0},
	{enemy: 0},
	{radius: 0},
	{Bullet: 0},
	{bullet: 0},
	{bulleteffect: 0},
	{BackgroundSubMateri: 0},
	{tombol_materi: 0},
	{materi: 0},
	{cutscene_background: 0},
	{cutscene_element: 0},
	{cutscene_text: 0},
	{mission_pape: 0},
	{bintang: 0},
	{fall: 0},
	{caramain: 0},
	{state_components: 0},
	{menuComponent: 0},
	{menu_state: 0},
	{audio: 0},
	{info_number: 0},
	{fullscreen: 0},
	{picked: 0},
	{level: 0},
	{pilih_state: 0},
	{KEY_LEVEL: 0},
	{question: 0},
	{item: 0},
	{skor: 0},
	{item_picked: 0},
	{pause: 0},
	{karakter: 0},
	{revealed: 0},
	{health: 0},
	{materi_state: 0},
	{frame: 0}
];

self.InstanceType = {
	IMG_: class extends self.ISpriteInstance {},
	IMG_2: class extends self.ISpriteInstance {},
	IMG_3: class extends self.ISpriteInstance {},
	IMG_4: class extends self.ISpriteInstance {},
	IMG_5: class extends self.ISpriteInstance {},
	IMG_6: class extends self.ISpriteInstance {},
	IMG_7: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	tombol: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	tr1: class extends self.ITiledBackgroundInstance {},
	tr2: class extends self.ITiledBackgroundInstance {},
	headline: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	info_layer: class extends self.ISpriteInstance {},
	tokoh: class extends self.ISpriteInstance {},
	savegame: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	solids: class extends self.ISpriteInstance {},
	IMG_8: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	profil: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	ambil_btn: class extends self.ISpriteInstance {},
	IMG_9: class extends self.ISpriteInstance {},
	dark: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	jeda: class extends self.ISpriteInstance {},
	questionBox: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	funfact: class extends self.ISpriteInstance {},
	tracker: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	radius: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	bulleteffect: class extends self.IParticlesInstance {},
	BackgroundSubMateri: class extends self.ISpriteInstance {},
	tombol_materi: class extends self.ISpriteInstance {},
	materi: class extends self.ISpriteInstance {},
	cutscene_background: class extends self.ISpriteInstance {},
	cutscene_element: class extends self.ISpriteInstance {},
	cutscene_text: class extends self.ISpriteInstance {},
	mission_pape: class extends self.ISpriteInstance {},
	bintang: class extends self.ISpriteInstance {},
	fall: class extends self.ISpriteInstance {},
	caramain: class extends self.ISpriteInstance {},
	menuComponent: class extends self.ISpriteInstance {}
}